baseURL = 'https://kruemelmann.github.io/'
languageCode = 'en-us'
title = 'kruemelmann'
theme = "kruemelmann"

[params]
  author = "kruemelmann"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/bootstrap'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/font-awesome'
[[module.imports]]
    path = 'github.com/hugomods/icons/vendors/simple-icons'
